qemu-system-x86_64 \
  -machine type=q35,accel=hvf:kvm:tcg \
  -cpu max \
  -smp 2 \
  -m 6G \
  -device e1000,netdev=user.0,addr=0x03 \
  -netdev user,id=user.0,ipv6=off \
  -device qemu-xhci \
  -device usb-tablet \
  -device nec-usb-xhci,id=usb-controller-0 \
  -boot strict=off \
  -bios "$QVM_CACHE/share/qemu/bios-256k.bin" \
  -device virtio-scsi-pci \
  -device scsi-hd,drive=drive0,bootindex=0 \
  -drive if=none,file="$VM_IMAGE",id=drive0,cache=unsafe,discard=ignore,format=qcow2
